version: "3"
services:
  spring:
    build: docker/spring
    volumes:
      - .:/usr/local/myexpenses
    container_name: myexpenses-api
    ports:
      - "8080:8080"
    depends_on:
      - "dbserver"
    env_file:
      - docker/docker-vars.env
  dbserver:
    build: docker/mysql
    ports:
      - "33060:3306"
    env_file:
      - docker/docker-vars.env
    volumes:
      - /var/lib/mysql
    container_name: myexpenses-mysql